# settings for rom-manager

mame_data_file: '/usr/local/games/mame/mame.xml'
#fbneo_data_file: '/usr/local/games/fbneo/support/lists/dat/FBNeo_-_Arcade.dat'
mame_rom_path: '/mnt/space/Games/mame/'

remote_hw:
  deck:
    name: 'Steamdeck'
    protocol: 'ssh'
    ip_addr: '192.168.1.219'
    port: '22'
    user: 'deck'
    rom_path: '/home/deck/Emulation/roms'
  vita:
    name: 'Playstation Vita'
    protocol: 'ftp'
    ip_addr: '192.168.1.39'
    port: '1337'
    user: 'anonymous'
    passwd: 'nobody@nowhere.invalid'
    rom_path: '/uma0:/roms'
  pi4:
    name: 'Raspberry Pi 4'
    protocol: 'ssh'
    ip_addr: '192.168.1.21'
    port: '22'
    user: 'pi'
    rom_path: '/home/pi/roms'

country_list:
  - 'USA'
  - 'France'
  - 'Europe'
  - 'World'
  - 'Japan'

banned_words:
  - 'BIOS'
  - 'Enhancement Chip'
  - 'Homebrew'
#  - '(Unl'
  - '(Proto'
  - '(Pirate'
  - '(Demo'
  - '(Hack'
  - '(Program'
  - '(Beta'
  - '(NP'
  - '(Alt'
  - '(Sample'
  - '(Germany)'
  - '(Italy)'
  - '(Spain)'
  - 'Virtual Console'
  - 'Switch Online'
  - 'Sega Channel'
  - 'Classic Collection'
  - '(Test Program)'

banned_arcade_games:
  # bootlegs
  - 39in1
  - aladmdb
  - backfirt
  - barek3mb
  - black
  - bldyr3b
  - brod
  - chry10
  - cpokerpk
  - cps3boot
  - crswd2bl
  - denseib
  - empcity
  - endless
  - ffight2b
  - froman2b
  - fspiderb
  - gmgalax
  - igromult
  - iron
  - janputer
  - jparkmb
  - kbash2
  - kinstb
  - kok
  - lasthope
  - legendsb
  - lucky74
  - m4tupen
  - mjreach
  - mk3mdb
  - mk3snes
  - moguchan
  - mstworld
  - pengadvb
  - pesadelo
  - protennb
  - rushbets
  - sblast2b
  - shinfz
  - slotunbl
  - smssgame
  - smssgamea
  - sonic2mb
  - srmdb
  - ssf2mdb
  - tetrbx
  - tetriskr
  - tourvis
  - twinktmb
  - venom
  - zigzagb
  - zintrckb
  - bootleg_sys16a_sprite
  - seibu_cop_boot
  - neocart_matrimbl
  - neocart_kof10th
  - neocart_kof2002b
  - neocart_kf2k3bl
  - neocart_boot
  - neocart_garoubl
  - neocart_kof97oro
  - neocart_kf10thep
  - neocart_kf2k5uni
  - neocart_kf2k4se
  - neocart_lans2004
  - neocart_samsho5b
  - neocart_mslug3b6
  - neocart_ms5plus
  - neocart_kog
  - neocart_svcboot
  - neocart_svcplus
  - neocart_svcplusa
  - neocart_svcsplus
  - ng_cthd_prot
  - ng_kof2k3bl_prot
  - ngboot_prot
  - nes_mbaby
  - nes_asn
  # korea
  - atomicp
  - bongo
  - hexa
  - jpopnics
  - mimonkey
  - ozon1
  - snapper
  - tetrsark
  # fishing
  - seabass
  - sfish2
  # gun
  - bel
  - duckhunt
  - gunblade
  - hogalley
  - hotd
  - le2
  - opwolf
  - rchase2
  - vcop
  - vcop2
  - von
  - vsfdf
  # mahjong
  - 4psimasy
  - 7jigen
  - akiss
  - av2mj1bb
  - av2mj2rg
  - bakatono
  - bananadr
  - cafebrk
  - cafedoll
  - cafepara
  - cafetime
  - chinmoku
  - club90s
  - cmehyou
  - csplayh1
  - csplayh5
  - csplayh6
  - cultures
  - daimyojn
  - daireika
  - daiyogen
  - danchih
  - dondenmj
  - dtoyoken
  - dunhuang
  - emjjoshi
  - emjscanb
  - emjtrapz
  - froman2b
  - fromanc2
  - fromanc4
  - fromance
  - fromancr
  - gakusai
  - gakusai2
  - gal10ren
  - galkaika
  - galkoku
  - gekisha
  - goodejan
  - hanamomo
  - hotgmcki
  - hourouki
  - hypreac2
  - hypreact
  - idolmj
  - imekura
  - janbari
  - janjans1
  - janjans2
  - janputer
  - janshinp
  - jantotsu
  - jituroku
  - jjparads
  - jjparad2
  - jogakuen
  - jongbou
  - jongtei
  - jyangoku
  - kaguya
  - kaguya2
  - kakumei
  - kakumei2
  - kisekaem
  - kiwame
  - kiwames
  - koinomp
  - korinai
  - lemnangl
  - lhzb2
  - mahjngoh
  - mahmajn
  - mahmajn2
  - mahretsu
  - majrjhdx
  - majs101b
  - majxtal7
  - mcnpshnt
  - mcontest
  - mfightc
  - mfunclub
  - mgakuen
  - mgakuen2
  - mgcs
  - mgdh
  - mgmen89
  - mhgaiden
  - mhhonban
  - minasan
  - mirage
  - mj1
  - mj2
  - mj3
  - mj3evo
  - mj3evoup
  - mj4simai
  - mjangels
  - mjcamera
  - mjcamerb
  - mjchuuka
  - mjclinic
  - mjclub
  - mjcomv1
  - mjdchuka
  - mjdejavu
  - mjderngr
  - mjdialq2
  - mjdiplob
  - mjegolf
  - mjelctrn
  - mjflove
  - mjfocus
  - mjfriday
  - mjgaiden
  - mjgalpri
  - mjgnight
  - mjgottsu
  - mjgottub
  - mjgtaste
  - mjhokite
  - mjifb
  - mjikaga
  - mjjoship
  - mjkinjas
  - mjkjidai
  - mjkoiura
  - mjkojink
  - mjlaman
  - mjlstory
  - mjmaglmp
  - mjmania
  - mjmyorn2
  - mjmyster
  - mjmyuniv
  - mjnanpas
  - mjnatsu
  - mjnquest
  - mjprivat
  - mjreach
  - mjreach1
  - mjschuka
  - mjsenka
  - mjsenpu
  - mjsikaku
  - mjsister
  - mjsiyoub
  - mjtensin
  - mjuraden
  - mjvegasa
  - mjyarou
  - mjyougo
  - mjyuugi
  - mjzoomin
  - mkeibaou
  - mladyhtr
  - mmehyou
  - mmmbanc
  - mogitate
  - momotaro
  - mrokumei
  - mscoutm
  - msjiken
  - myfairld
  - neruton
  - nmsengen
  - ntopstar
  - otatidai
  - othellos
  - otonano
  - ougonhai
  - pachiten
  - patimono
  - ponchin
  - pss62
  - pstadium
  - ptrmj
  - qmhayaku
  - renaiclb
  - renaimj
  - rmhaihai
  - rmhaijin
  - rmhaisei
  - ron2
  - royalmj
  - ryouran
  - sailorws
  - scandal
  - sdmg2
  - sengokmj
  - sengomjk
  - shabdama
  - shanhigw
  - slqz2
  - slqz3
  - srmp1
  - srmp2
  - srmp3
  - srmp4
  - srmp5
  - srmp6
  - srmp7
  - srmvs
  - sryudens
  - taiwanmb
  - teljan
  - telmahjn
  - tenkai
  - themj
  - tjsb
  - tmmjprd
  - tonpuu
  - triplew1
  - triplew2
  - uchuuai
  - ultramhm
  - urashima
  - usagiym
  - vanilla
  - vitaminc
  - vmahjong
  - vsmahjng
  - wcatcher
  - yarunara
  - yosimoto
  - nb1412m2
  - nb1413m3
  - nb1414m4
  - md_rom_mjlov
  - md_rom_cjmjclub
  - neogeo_mj_ac
  - neogeo_mj
  - nes_txc_mjblock
  - nes_mjpanel
  # prototype
  - 3on3dunk
  - airrace
  - akkaarrh
  - androidp
  - arcadecl
  - argusg
  - asylum
  - b85cb7p
  - barata
  - barbball
  - bbprot
  - beathead
  - biofreak
  - bombsa
  - bowarrow
  - boxer
  - bygone
  - c264
  - c65
  - calcune
  - catchp
  - cball
  - chimerab
  - clcd
  - cloud9
  - commandw
  - cue
  - cybstorm
  - dankuga
  - demndrgn
  - diggerma
  - divebomb
  - doraemon
  - dualgame
  - firebeas
  - fishfren
  - flicker
  - freezeat
  - galgame4
  - gemcrush
  - ghostlop
  - guts
  - hamaway
  - hangzo
  - hdrivair
  - insector
  - inyourfa
  - ironclad
  - ixion
  - j6hisprt
  - jumpkun
  - kngtmare
  - laststar
  - lemmings
  - m3scoop
  - madmotor
  - marvland
  - mazeinv
  - metalmx
  - mgolf
  - moonwarp
  - mtouchxl
  - nms8260
  - orbatak
  - orbs
  - packbang
  - pastelis
  - pc_bload
  - pc_ttoon
  - playball
  - popshot
  - pprobe
  - pr_trktp
  - puzlclub
  - pzletime
  - qb3
  - qwak
  - recalh
  - rockduck
  - rockn4
  - rotr
  - rrreveng
  - runaway
  - sc1cshat
  - sc2cexpl
  - sc2cgc
  - screwloo
  - shrike
  - sparkz
  - spdball
  - spdcoin
  - sqbert
  - strax_p7
  - strtdriv
  - tankbatl
  - tattass
  - teetert
  - tenthdeg
  - toggle
  - tomcat
  - toratora
  - tshoot
  - turbosub
  - turbotag
  - twinqix
  - tylz
  - v4vgpok
  - vcircle
  - vdogdeme
  - vdogdemo
  - vidvince
  - warpsped
  - wingforc
  - wizwarz
  - wolfpack
  - xorworld
  - np600a3
  - c64_4cga
  - aic6250
  - aic6251a
  # purikura
  - nameclub
  - nclubv2
  - nclubv3
  - pckobe99
  - pclb2elk
  - pclove
  - pclove2
  - pclub
  - pclub2
  - pclub26w
  - pclub26wa
  - pclub27s
  - pclub2fc
  - pclub2kc
  - pclub2pe
  - pclub2pf
  - pclub2v3
  - pclub2wb
  - pclubj
  - pclubjv2
  - pclubjv4
  - pclubjv5
  - pclubol
  - pclubor
  - pclubpok
  - pclubyo2
  - pcpooh2
  - pcpooh3
  - prc28su
  - prc297wi
  - prc297wia
  - prc298au
  - prc298sp
  - prc298su
  - prc29au
  - prc2ksu
  - prikura
  # quizzes
  - atamanot
  - atehate
  - bkrtmaq
  - cashquiz
  - cgangpzl
  - coronatn
  - cworld
  - cworld2j
  - danchiq
  - dquizgo
  - dquizgo2
  - ejihon
  - fbcrazy
  - funquiz
  - funquiza
  - funquizb
  - gakupara
  - gekiretu
  - gp2quiz
  - gulunpa
  - hatena
  - hayaosi1
  - hayaosi2
  - hayaosi3
  - hotdebut
  - hyhoo
  - hyhoo2
  - inquiztr
  - introdon
  - inufuku
  - kaiunqz
  - keithlcy
  - kokoroj
  - kokoroj2
  - ldquiz4
  - livequiz
  - lsrquiz
  - lsrquiz2
  - macha
  - magzun
  - marukodq
  - mdhorse
  - mv1cwq
  - myangel
  - myangel2
  - myangel3
  - nettoqc
  - qad
  - qcrayon
  - qcrayon2
  - qdrmfgp
  - qdrmfgp2
  - qgakumon
  - qgh
  - qgundam
  - qjinsei
  - qkracer
  - qmegamis
  - qmhayaku
  - qndream
  - qrouka
  - qsangoku
  - qsww
  - qtheater
  - qtono1
  - qtono2j
  - qtorimon
  - quaquiz2
  - quiz
  - quiz18k
  - quiz211
  - quiz365
  - quizard
  - quizard2
  - quizard3
  - quizard4
  - quizchq
  - quizdai2
  - quizdais
  - quizdna
  - quizf1
  - quizhq
  - quizhuhu
  - quizkof
  - quizmeku
  - quizmoon
  - quizmstr
  - quizo
  - quizpani
  - quizpun
  - quizpun2
  - quizqgd
  - quizshow
  - quiztou
  - quiztvqq
  - quizvadr
  - quizvid
  - quizwizc
  - qzchikyu
  - qzkklgy2
  - qzkklogy
  - qzquest
  - qzshowby
  - ryorioh
  - sukuinuf
  - sunaq
  - supertr
  - trivquiz
  - wizzquiz
  - xsedae
  - yesnoj
  - yuyugogo
  # rejects
  - 1943mii
  - 3in1semi
  - 3stooges
  - 4dwarrio
  - 4in1boot
  - alienar
  - arescue
  - atomicp
  - bakutotu
  - ballbros
  - blazer
  - blitz
  - blitz99
  - blitz2k
  - boxyboy
  - brain
  - bubbletr
  - bwcasino
  - cannonbp
  - carnevil
  - catacomb
  - chinatwn
  - cleopatr
  - clubpacm
  - cookbib2
  - cookbib3
  - cosmo
  - crazyfgt
  - critcrsh
  - crswd2bl
  - cupfinal
  - curvebal
  - daiskiss
  - dakkochn
  - dangseed
  - dbldynj
  - dbzvrvs
  - dcclub
  - deerhunt
  - dmnfrnt
  - dokaben
  - dragngun
  - dragonsh
  - dremshpr
  - drgnbowl
  - drgw2
  - dw2001
  - dwpc
  - enmadaio
  - eggor
  - eto
  - euroch92
  - faceoff
  - fantastc
  - fball
  - finallap
  - finalttr
  - finehour
  - gardia
  - gauntdl
  - gauntleg
  - godzilla
  - gollygho
  - gulunpa
  - gunlock
  - hal21
  - happy6
  - harddunk
  - hvymetal
  - hwrace
  - hyperpac
  - imsorry
  - intcup94
  - invrvnge
  - isgsm
  - ixion
  - janshin
  - jdreddp
  - jin
  - jitsupro
  - jockeygp
  - jpark
  - jpopnics
  - kicknrun
  - kirameki
  - korokoro
  - koshien
  - krull
  - kyukaidk
  - kyustrkr
  - landmakr
  - legend
  - lghost
  - lightbr
  - loffire
  - lockload
  - lottofun
  - luctoday
  - luckywld
  - mach3
  - madshark
  - martmast
  - mastkin
  - mayday
  - metlhawk
  - micrombc
  - mmaze
  - mmonkey
  - moremore
  - moremorp
  - moshougi
  - mplanets
  - mrtnt
  - nbagold
  - nbanfl
  - nbashowt
  - neobattl
  - netmerc
  - nob
  - oisipuzl
  - othldrby
  - orbitron
  - ordyne
  - orlegend
  - patocar
  - pbobble
  - pbobble2
  - penbros
  - pgm
  - photoy2k
  - pisces
  - pistoldm
  - prmrsocr
  - ptblank
  - puchicar
  - puzlstar
  - puzzli2
  - pwrgoal
  - pzlbowl
  - pzlbreak
  - qbertqub
  - quester
  - raflesia
  - rascot2
  - razmataz
  - rbislande
  - reactor
  - rmpgwt
  - rocktrv2
  - roishtar
  - rompers
  - ryujin
  - ryukyu
  - sackids
  - sandor
  - sbm
  - scross
  - sdtennis
  - sf2049
  - sf2049se
  - sf2049te
  - sf2t
  - sfposeid
  - sfx
  - sfrush
  - sfrushrk
  - sfzch
  - sgmast
  - sgunner
  - sgunner2
  - shadowld
  - shinfz
  - shootgal
  - shtngmst
  - sjryuko
  - skybase
  - skychal
  - skytargt
  - snapper
  - snowbro3
  - sokonuke
  - spacecr
  - spaceskr
  - spatter
  - spcfrcii
  - spclforc
  - spcewarl
  - spdball
  - spdcoin
  - spyhunt2
  - srdmissn
  - stakwin
  - stakwin2
  - stakwindev
  - stress
  - supbtime
  - superbon
  - svg
  - tcobra2
  - tdpgal
  - tdfever
  - tetrsark
  - theglad
  - titlef
  - tokisens
  - toppyrap
  - toryumon
  - toto
  - trophyh
  - trstar
  - tstrike
  - turkhunt
  - twinkle
  - twinqix
  - twsoc96
  - ufosensi
  - umanclub
  - usvsthem
  - utoukond
  - vanvan
  - vliner
  - vshoot
  - vsnetscr
  - waterski
  - wits
  - wldcourt
  - wmatch
  - wofch
  - woodpeck
  - worldwar
  - ws
  - wschamp
  - wtennis
  - wwallyj
  - xday2
  - zombraid
