# settings for rom-manager

country_list:
  - 'USA'
  - 'France'
  - 'Europe'
  - 'World'
  - 'Japan'

banned_words:
  - 'BIOS'
  - 'Enhancement Chip'
  - '(Unl'
  - '(Demo'
  - '(Hack'
  - '(Program'
  - '(Beta'
  - '(NP'
  - '(Alt'
  - '(Sample'
  - '(Germany)'
  - '(Italy)'
  - '(Spain)'
  - 'Virtual Console'
  - 'Switch Online'
  - 'Sega Channel'
  - 'Classic Collection'

remote_hw:
  deck:
    name: 'Steamdeck'
    protocol: 'ssh'
    ip_addr: '192.168.1.219'
    port: '22'
    user: 'deck'
    rom_path: '/home/deck/Emulation/roms'
  vita:
    name: 'Playstation Vita'
    protocol: 'ftp'
    ip_addr: '192.168.1.12'
    port: '1337'
    user: 'anonymous'
    rom_path: 'uma0:/roms'
