# settings for rom-manager

mame_data_file: 'mame.xml'
#fbneo_data_file: []
mame_rom_path: 'roms/'

remote_hw:
  deck:
    name: 'Steamdeck'
    protocol: 'ssh'
    ip_addr: '192.168.1.2'
    port: '22'
    user: 'deck'
    rom_path: '/home/deck/Emulation/roms'
  vita:
    name: 'Playstation Vita'
    protocol: 'ftp'
    ip_addr: '192.168.1.3'
    port: '1337'
    user: 'anonymous'
    passwd: 'nobody@nowhere.invalid'
    rom_path: '/uma0:/roms'
  pi4:
    name: 'Raspberry Pi 4'
    protocol: 'ssh'
    ip_addr: '192.168.1.4'
    port: '22'
    user: 'pi'
    rom_path: '/home/pi/roms'
  sdcard:
    name: 'SD Card'
    protocol: 'local'
    ip_addr: None
    port: None
    user: None
    rom_path: '/home/user/ROMs'

mame_merged_roms: True

replace_roms:
  simpsons: 'simpsons2p3'
  ssriders: 'ssridersebd'
  tmnt: 'tmht2p'
  tmnt2: 'tmnt22pu'
  vendetta: 'vendetta2pw'
  xmen: 'xmen2pe'

allow_translations: True

country_list:
  - 'USA'
  - 'Europe'
  - 'World'
  - 'Japan'

banned_words:
  - '(Alt'
  - '(Beta'
  - '(Demo'
  - '(Hack'
  - '(Kiosk)'
  - '(NP'
  - '(Pirate'
  - '(Program'
  - '(Sample'
  - '(Test Program)'
  - 'BIOS'
  - 'Classic Collection'
  - 'Enhancement Chip'
  - 'Sega Channel'
  - 'Switch Online'
  - 'Virtual Console'

banned_arcade_games:
  - nameclub
  - nclubv2
  - nclubv3
